
# filegroup(
#     name = "Example",
#     srcs = ["example.mobileprovision"],
#     visibility = ["//visibility:public"]
# )

filegroup(
    name = "Example",
    srcs = ["9820e2fa-b4d5-4ed4-af74-acc83803a7b3.mobileprovision"],
    visibility = ["//visibility:public"]
)